const ACTIONS = {
  THEME_SWITCH: 'THEME_SWITCH',

  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',

  SIGN_UP_USER_REQUEST: 'SIGN_UP_USER_REQUEST',
  SIGN_UP_USER_SUCCESS: 'SIGN_UP_USER_SUCCESS',
  SIGN_UP_USER_ERROR: 'SIGN_UP_USER_ERROR',

  AUTHENTICATE_REQUEST: 'AUTHENTICATE_REQUEST',
  AUTHENTICATE_ERROR: 'AUTHENTICATE_ERROR',
  AUTHENTICATE_SUCCESS: 'AUTHENTICATE_SUCCESS',

  SIGN_OUT: 'SIGN_OUT',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',

  GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
  GET_POSTS_ERROR: 'GET_POSTS_ERROR',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',


  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
};

export default ACTIONS;
