const ACTIONS = {
  THEME_SWITCH: Symbol('THEME_SWITCH'),

  LOGIN_USER_REQUEST: Symbol('LOGIN_USER_REQUEST'),
  LOGIN_USER_SUCCESS: Symbol('LOGIN_USER_SUCCESS'),
  LOGIN_USER_ERROR: Symbol('LOGIN_USER_ERROR'),

  SIGN_UP_USER_REQUEST: Symbol('SIGN_UP_USER_REQUEST'),
  SIGN_UP_USER_SUCCESS: Symbol('SIGN_UP_USER_SUCCESS'),
  SIGN_UP_USER_ERROR: Symbol('SIGN_UP_USER_ERROR'),

  SIGN_OUT: Symbol('SIGN_OUT'),
};

export default ACTIONS;
